
---
title: "Penguins"
format: html
knitr:
  opts_chunk: 
    collapse: true
    R.options:
    message: false
    echo: false
    warning: false
    code-fold: false
---

Utilizzare il dataset `penguins` parte del package `palmerpenguins`

```{r}
library(tidyverse)
library(palmerpenguins)
library(tidymodels)
library(janitor)
library(kableExtra)

pengs = penguins %>% na.omit()

# Visualize sample
pengs %>% slice_sample(n=10) %>% kbl()
```

## Normalised Asymmetry for bill_length and bill_depth

```{r}
asymmetry = pengs %>%
  group_by(species) %>%
  summarise(
    bill_length_asym = (mean(bill_length_mm) - median(bill_length_mm)) / sd(bill_length_mm),
    bill_depth_asym = (mean(bill_depth_mm) - median(bill_depth_mm)) / sd(bill_depth_mm)
  )
asymmetry %>% kbl()
```

## Measurements on Torgersen Island

```{r}
torgersen_count = pengs %>%
  filter(island == "Torgersen") %>%
  summarise(count = n())
torgersen_count %>% kbl()
```

## Scatterplot of bill_length vs bill_depth

```{r}
pengs = pengs %>%
  mutate(bmi = body_mass_g / (flipper_length_mm^2))

ggplot(pengs, aes(x = bill_length_mm, y = bill_depth_mm, size = bmi, color = species)) +
  geom_point(alpha = 0.7) +
  theme_minimal() +
  labs(title = "Bill Length vs Bill Depth with BMI", x = "Bill Length (mm)", y = "Bill Depth (mm)", size = "BMI")
```
